<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8oXLNQ\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8oXLNQ/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerR8oXLNQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerR8oXLNQ\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerR8oXLNQ\srcApp_KernelProdContainer([
    'container.build_hash' => 'R8oXLNQ',
    'container.build_id' => '587f5f2f',
    'container.build_time' => 1583025022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8oXLNQ');
