<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \App\Entity\Invoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'invoicenumber', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'footer', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'line', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'subtotal', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'total', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'enterprise', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'visible'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'invoicenumber', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'footer', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'line', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'subtotal', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'total', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'enterprise', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'visible'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Invoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicenumber(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicenumber', []);

        return parent::getInvoicenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoicenumber(int $invoicenumber): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoicenumber', [$invoicenumber]);

        return parent::setInvoicenumber($invoicenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getFooter(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFooter', []);

        return parent::getFooter();
    }

    /**
     * {@inheritDoc}
     */
    public function setFooter(string $footer): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFooter', [$footer]);

        return parent::setFooter($footer);
    }

    /**
     * {@inheritDoc}
     */
    public function getLine(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine', []);

        return parent::getLine();
    }

    /**
     * {@inheritDoc}
     */
    public function addLine(\App\Entity\ProductLine $line): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLine', [$line]);

        return parent::addLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLine(\App\Entity\ProductLine $line): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLine', [$line]);

        return parent::removeLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', []);

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal(float $subtotal): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', [$subtotal]);

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal(float $total): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient(): ?\App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(?\App\Entity\Client $client): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnterprise(): ?\App\Entity\Enterprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnterprise', []);

        return parent::getEnterprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnterprise(?\App\Entity\Enterprise $enterprise): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnterprise', [$enterprise]);

        return parent::setEnterprise($enterprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible(bool $visible): \App\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

}
