<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM8FhJV5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM8FhJV5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM8FhJV5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM8FhJV5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM8FhJV5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M8FhJV5',
    'container.build_id' => 'e15eaf5a',
    'container.build_time' => 1583701453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM8FhJV5');
